  <footer>
        <h2 class="footer_brand_name center">3Ners Corp</h2>
        <div class="footer_details">
            <section class="colum"> <!-- Contact -->
                <h4 class="footer_title">Contact us</h4>
                <ul>
                    <li>Email: <a href="#">info@companyname.com.au</a></li>
                    <li>Jira: <a href="https://cos10026-3ners.atlassian.net/jira/software/projects/SCRUM/boards/1">COS10026 - Group 1</a></li>
                    <li>Github: <a href="https://annnk137.github.io/project1/">Github Page</a></li>
                    <li>Github Repo: <a href="https://github.com/AnnNK137/project1">3Ners Project 1</a></li>
                </ul>
            </section>
            <section class="colum"> <!-- navigation bar -->
                <h4 class="footer_title">Navigation</h4>
                <ul class="center">
                    <li><a href="index.php">Home</a></li>
                    <li><a href="jobs.php">Job Info</a></li>
                    <li><a href="apply.php">Applying</a></li>
                    <li><a href="about.php">About</a></li>
                </ul>
            </section>
        </div>
    </footer>