     <header id="header">
         <nav>
            <a href="index.php" class="brand_logo">
                <img src="images/logo.png" alt="3Ners">    
                HR Management          
            </a>
             <ul class="nav_items">
                <li><a href="manage.php">Applicants</a></li>
                <li><a href="hr_profile.php">Profile</a></li>
             </ul>
         </nav>
     </header>