     <header id="header">
         <nav>
            <a href="index.php" class="brand_logo">
                <img src="images/logo.png" alt="3Ners">              
            </a>
             <ul class="nav_items">
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Job</a></li>
                <li><a class="nav_current" href="apply.php">Applying</a></li>
                <li><a href="about.php">About</a></li>
             </ul>
         </nav>
     </header>